stancsz:
  name: Stan Chen
  email: bytenrecords+stan@gmail.com
  role: owner of byten records
  jobs:
    - assign tasks for artists in byten, come up with song ideas
    - in my outoutput, think about what to do next
meganlyc:
  name: Megan Li
  email: bytenrecords+megan@gmail.com
  role: artist/lyrics writer of byten records
# kyoichitsu:
#   name: kyoichitsu
#   email: bytenrecords+kyoichi@gmail.com
#   role: producer/artist/lyrics writer of byten records
# essoria:
#   name: Isadora Lee
#   email: bytenrl+isadora@gmail.com
#   role: female artist/lyrics writer of byten records
# andrewpan:
#   name: Andrew Pan
#   email: bytenrl+andrew@gmail.com
#   role: manager/writer/qc of byten records