import os
from openai import OpenAI

def generate_response(user_input):
    """
    Generate a response from the OpenAI GPT-4o-mini model based on the user's input.

    Args:
        user_input (str): The input prompt from the user.

    Returns:
        str: The response generated by the model.
    """
    # Initialize the OpenAI client with your API key
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    # Define the system message content
    system_message_content = (
        "multi-agent system. follow instructions in each agent's job prompt"
    )

    # Create the chat completion request
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_message_content},
            {"role": "user", "content": user_input}
        ],
        response_format={"type": "text"},
        temperature=1,
        max_tokens=2048,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0
    )

    # Extract and return the assistant's response
    return response.choices[0].message.content